config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :surveys, only: [:destroy, :create, :index, :new, :show]
  resources :data, only: [:index, :show]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, "ヘルプ（説明）") %>

<div class="help">

<h1>このサイトについて</h1>

<h2>水しるべ調査成果共有プラットフォーム（試験運用中）</h2>
<p>
このサイトは各地で行われている<%= link_to "水環境健全性指標(水しるべ調査)", "https://www.env.go.jp/water/wsi/", target: "_blank" %>の成果を
共有する目的で、<%= link_to "日本水環境学会東北支部", "http://jswetohoku.web.fc2.com/", target: "_blank" %>が運用しています。
</p>

<h2>試験運用にご協力をお願いします</h2>
<p>水しるべ調査の成果を共有するプラットフォームの構築を目指して、2017年12月から試験運用を開始しています。
試験運用中のご利用は自由ですが、以下の点にご注意ください。</p>

<ul>
<li>不定期にサービスが停止する場合があります。 </li>
<li>ページのデザインや機能が変更される場合があります。</li>
<li>登録したデータが変更・削除される場合があります。</li>
</ul>

<p>不具合等を発見された場合は、下記問合せ先までお知らせください。</p>


<h2>問い合わせ先</h2>
<p><%= link_to "日本水環境学会東北支部", "http://jswetohoku.web.fc2.com/", target: "_blank" %></p>
<ul>
<li>東北工業大学 矢野篤男 yano-t@tohtech.ac.jp (代表)</li>
<li>(元)青森県環境管理事務所 三上一 h.mikaml32@gmail.com</li>
<li>青森大学 角田均 tsunoda@aomori-u.ac.jp (システム開発担当)</li>
</ul>

<h1>操作方法</h1>

<h2>ホームのマップ操作</h2>
<ul>
    <li>このWebアプリはIEは非推薦です。Chrome等のブラウザを利用してください。</li>
    <li>マウスのホイールボタンで拡大縮小ができます。</li>
    <li>地図のドラック＆ドロップで移動できます。</li>
    <li>下のボタンで表示を切り替えることができます。</li>
    <%= image_tag("map1.png")%>
</ul>

<h2>調査一覧の表示</h2>
<ul>
    <li>調査名または、調査地点名をクリックすると詳細データを表示します。</li>
    <li>ログインしていると自分が登録した調査データの削除ができます。</li>
    <%= image_tag("index1.png")%>
</ul>

<h2>アカウントの新規登録</h2>
<ol>
    <li>「<%= link_to "ログイン", login_path %>」をクリック、一番下の「<%= link_to "新規登録はこちらから", signup_path %>」をクリック。
    <%= image_tag("sinki1.png")%></li>
    <li>名前、メールアドレス、パスワード（2回）を入力して、登録ボタンを押す。
    <%= image_tag("sinki2.png")%></li>
    <li>新しいユーザーアカウントが作成されます。</li>
</ol>

<h2>ログイン</h2>
<ul>
    「<%= link_to "ログイン", login_path %>」をクリック、情報を入力してログインできます。
    <%= image_tag("rogu1.png")%>
</ul>

<h2>アカウントの削除</h2>
<ul>
    アカウントを削除するには「ユーザー情報」から、「自分のアカウントを削除」で削除できます。
    <%= image_tag("userdelete1.png")%>
</ul>

<h2>登録用CSVファイルの作り方</h2>
<ol>
    <li><a href="/Template.zip">こちら</a>からひな型のファイル（圧縮ファイル）をダウンロードします。
        <p><a href="/Template.zip">Microsoft Excelのテンプレート（圧縮ファイル）をダウンロード</a></p></li>
    <li>ダウンロードした圧縮ファイルを解凍、「Template(テンプレート).xlsx」の中に見本を参考にして調査データを記入します。
        <%= image_tag("csv2_1.png")%></li>
    <li>「CSV形式」で名前を付けて保存します。<br>
        エクセルのデータをCSV形式で保存するには「ファイルの種類」でCSVを選択しするとCSV形式にできます。<br>
        （注意）登録用CSVファイルの文字コードはWindows形式（CP932、シフトJIS）です。
        <%= image_tag("csv2_2.png")%>
        <%= image_tag("csv2_3.png")%></li>
</ol>

<h2>調査データの登録</h2>
<ol>
    <li>調査データを登録するには<%= link_to "ログイン", login_path %>している必要があります。
        ログインするには、最初に「<%= link_to "新規登録はこちら", signup_path %>」からアカウント登録してください。</li>
    <li>「<%= link_to "調査一覧", surveys_path %>」から、「<%= link_to "調査データを新規登録する", new_survey_path %>」ボタンをクリックします。
        <%= image_tag("touroku1.png")%></li>
    <li>「&#9312;調査名を記入」します。次に「&#9313;参照ボタンから登録したいCSVファイルを選択」して「&#9314;登録ボタンを押します」。
        <%= image_tag("touroku2.png")%></li>
</ol>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, "ホーム") %>

<script src="https://unpkg.com/popper.js"></script>

<!-- canvas -->
<div id="map-canvas"></div>

<div id="mode" class="btn-group" data-toggle="buttons">
	<label class="btn btn-primary">
		<input type="radio" autocomplete="off" value="0" name="item_select">自然のすがた
	</label>
	<label class="btn btn-primary">
		<input type="radio" autocomplete="off" value="1" name="item_select">豊かな生き物
	</label>
   	<label class="btn btn-primary">
		<input type="radio" autocomplete="off" value="2" name="item_select">水のきれいさ
	</label>
	<label class="btn btn-primary">
		<input type="radio" autocomplete="off" value="3" name="item_select">快適な水辺
	</label>
	<label class="btn btn-primary">
		<input type="radio" autocomplete="off" value="4" name="item_select">地域とのつながり
	</label>
	<label class="btn btn-primary active">
		<input type="radio" autocomplete="off" value="5" name="item_select">総合平均
	</label>
</div>

<!--
<%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSbQNYFqVhM8dgszl84006WpFVLy9FfEo&callback=initMap" async defer></script>	