config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :surveys, only: [:destroy, :create, :index, :new, :show]
  resources :data, only: [:index, :show]

end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <nav>
    <ul>
      <li>&copy; 2017 日本水環境学会東北支部</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "水しるべ調査（試験運用中）", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "調査一覧", surveys_path %></li>
        <li><%= link_to "ヘルプ（説明）", help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザー一覧", users_path %></li>
          <% end %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー情報", current_user %></li>
              <li><%= link_to "ユーザー情報の管理", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= yield(:title) %> | 水しるべ調査（試験運用中）</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>